Maskinporten exposes
navikt/helseopplysninger pull request #269
Opened 2021-08-11 11:07 UTC by emyklebost

2021-08-11 11:17 UTC, tronghn commented on apps/hops-api/.nais/maskinporten-client.yaml
> +  name: hops-maskinportenClient
Burde være lowercase

2021-08-11 11:17 UTC, tronghn commented on apps/hops-api/.nais/maskinporten-client.yaml
> +spec:
Trenger en `spec.secretName: <navn-på-secret>` slik at det opprettes en secret som dere kan hente ut

2021-08-12 07:04 UTC, mburgosh requested changes

2021-08-12 07:04 UTC, mburgosh commented on apps/hops-api/.nais/maskinporten-client.yaml
> +kind: MaskinportenClient
Hvordan spesifiserer vi at den klient skal få NAV sin orgno? skal vi også registrer klienter for EPJ leverandører etterhvert?

2021-08-12 07:14 UTC, emyklebost commented on apps/hops-api/.nais/maskinporten-client.yaml
> +      - name: "nav:helse/helseopplysninger.write"
fil avslutning? Tenker at de samme scopesene brukes for nedlasting\opplasting av filer også.

2021-08-12 07:17 UTC, mburgosh commented on apps/hops-api/.nais/maskinporten-client.yaml
> +      - name: "nav:helse/helseopplysninger.write"
Nei, bare en tom ligne, du kan endre din editor innstillinger for å altid lagge en tom ligne

2021-08-12 07:20 UTC, emyklebost commented on apps/hops-api/.nais/maskinporten-client.yaml
> +      - name: "nav:helse/helseopplysninger.write"
ah, visste ikke at betydde noe. Kanskje noe @rtc11 kan legge inn i den idea konfigen. Fjernet uansett denne filen nå siden jeg gjør det i en egen branch.

2021-08-12 07:21 UTC, emyklebost commented on apps/hops-api/.nais/maskinporten-client.yaml
> +kind: MaskinportenClient
nei, det gjøres av digidir, denne nais ressursen registrerer bare dette for oss (NAV).

2021-08-12 07:22 UTC, tronghn commented on apps/hops-api/.nais/maskinporten-client.yaml
> +kind: MaskinportenClient
Klienter opprettet via NAIS hører automatisk til under NAV sitt orgno. Nei, eksterne aktører må selv administrere og registrere klienter hos DigDir.

2021-08-12 07:28 UTC, merged