Feat/cdn test
navikt/helseopplysninger pull request #331
Opened 2021-09-02 10:01 UTC by mburgosh

- Bruke mock server for å mocke responser av ekstern servere. Mocker har happy-path satt opp.
- Bruke ktor config som hove conifg kilde, og hopslite for å kunne parse dem i type-safe data klasser

2021-09-02 10:48 UTC, emyklebost commented on apps/hops-fileshare/test/Helpers.kt
> +object Helpers {
Helpers er ikke særlig bra navn. MockServer kan f.eks trekkes ut i en egen fil og Helpers kan heller hete noe mer spesifikt, f.eks MockServerFactory elns.

2021-09-02 10:57 UTC, emyklebost commented on apps/hops-fileshare/main/fileshare/infrastructure/GCPHttpTransport.kt
>  class GCPHttpTransport(private val baseHttpClient: HttpClient, private val config: Config.FileStore) {
baseHttpClient brukes bare i init og trenger ikke være en property. Kan derfor skrive `baseHttpClient: HttpClient` istedenfor `private val baseHttpClient: HttpClient`

2021-09-02 10:59 UTC, emyklebost requested changes
se kommentarer

2021-09-02 11:59 UTC, mburgosh commented on apps/hops-fileshare/test/Helpers.kt
> +object Helpers {
Hva tenker du om `TestResources` men må også si at vi har de funksjoner som setter opp test server og config

2021-09-02 14:29 UTC, emyklebost commented on apps/hops-fileshare/test/MockServer.kt
> +    val mockWebServer = MockWebServer()
kan vel være private?

2021-09-02 14:32 UTC, emyklebost commented on apps/hops-fileshare/test/Helpers.kt
> +internal class KotestSetup : AbstractProjectConfig() {
Brukes denne?

2021-09-02 14:33 UTC, emyklebost commented on apps/hops-fileshare/test/Helpers.kt
> +    val fileInfoResponse = """
Kan være private?

2021-09-02 14:41 UTC, emyklebost commented on apps/hops-fileshare/test/Helpers.kt
> +object Helpers {
TestResources er også veldig generisk. Hva med å splitte ut i flere filer? Det som nå er object Helpers ser ut som en singleton med forskjellige MockServer instanser. Hvorfor ikke trekke dette ut i en egen fil og kalle singletonen MockServerInstances? Dette blir samtidig et naturlig scope og du trenger ikke repetere mockServer i navnene, f.eks får du da `MockServerInstances.gcs` istedenfor `Helpers.gcsMockServer`.

Resten av koden i filen ser ut til å være relatert til konfigurering av `TestApplicationEngine` vha. `withFileshareTestApp(...)`, dette kan trekkes ut i en egen fil som f.eks heter `TestApplicationEngine(Configurer|Bootstrapper|elns.)`

2021-09-03 05:45 UTC, rtc11 commented on apps/hops-fileshare/test/Helpers.kt
> +internal class KotestSetup : AbstractProjectConfig() {
Ja, med kotest kjøres ting i coroutines, så man må definere lyttere til kotest for at den ikke skal gå i beina på hverandre.

2021-09-03 05:53 UTC, rtc11 commented on apps/hops-fileshare/test/Helpers.kt
> +object Helpers {
Foreslår noe så enkelt som `MockServers`.

2021-09-03 07:26 UTC, mburgosh commented on apps/hops-fileshare/test/Helpers.kt
> +    val fileInfoResponse = """
den er i bruk av andre test: https://github.com/navikt/helseopplysninger/pull/331/files#diff-b65e559f2f8a437f1e57072bb4aed5cbaf1c68375abc2fa77345ce38a584aa7dR86

2021-09-03 07:29 UTC, mburgosh commented on apps/hops-fileshare/test/Helpers.kt
> +object Helpers {
Endret navn til MockServers og flyttet config funksjoner til TestEngineConigurer fil

2021-09-03 07:30 UTC, emyklebost approved these changes

2021-09-03 08:07 UTC, merged